### ISSUE TITLE
Some pre-trained models may be corrupted

### ISSUE THREAD

**Issue by fengfu-chris** [megvii-model/ShuffleNet-Series#1]
Hi, I downloaded the ShuffleNetV2.Large pre-trained model (snetv2_residual_se.pkl), but got the following message when loading the model in PyTorch:

RuntimeError: unexpected EOF, expected 1750141 more bytes. The file might be corrupted.

I have tried three times downloading the model, all get the same issue. So I think the problem may caused by the original source. The md5sum of the model which I download is:
be052a3ef97de2c64bc4236380972d38

Can you provide the md5sum of the original correct model? Many thanks.

**Comment by nmaac** [comment]
Hi fengfu-chris, we have re-uploaded this file and the md5sum is a68948fcdc791c2bbd237f0ec30dd968. Sorry for the corruption, please download it again thanks!

**Comment by fengfu-chris** [comment]
@nmaac Thanks for the updates. 

Now I find a new issue with the updated snet_detnas_l.pkl model. The weights of the last_conv layer in the pre-trained model has shape: [1728, 1728, 1, 1]; while the weights defined in the code has shape [1024, 1728, 1, 1]. Thus, it will cause a size mismatch problem: 

 size mismatch for last_conv.conv.weight: copying a param with shape torch.Size([1728, 1728, 1, 1]) from checkpoint, the shape in current model i
s torch.Size([1024, 1728, 1, 1])

I fixed this issue by change three lines of the code in DetNAS/network.py
1) stage_out_channels = [-1, 72, 172, 432, 864, 1728, 1728]  [https://github.com/megvii-model/ShuffleNet-Series/blob/5015a3b8ed6f031fdfcf6684eb9d6193cf1cb958/DetNAS/network.py#L22](url)
2) out_channel=stage_out_channels[-1] [https://github.com/megvii-model/ShuffleNet-Series/blob/5015a3b8ed6f031fdfcf6684eb9d6193cf1cb958/DetNAS/network.py#L55](url)
3) in_channels=stage_out_channels[-1] [https://github.com/megvii-model/ShuffleNet-Series/blob/5015a3b8ed6f031fdfcf6684eb9d6193cf1cb958/DetNAS/network.py#L58](url)

Please check it.

**Comment by nmaac** [comment]
@fengfu-chris  Thanks for checking, we fixed the DetNAS model.
