### ISSUE TITLE
About release the counter tools for flops

### ISSUE THREAD

**Issue by zxhr2793** [megvii-model/ShuffleNet-Series#12]
I have tried some tools [pytorch-OpCounter](https://github.com/Lyken17/pytorch-OpCounter) for calculate the flops and params of the released ShuffleNetV2, but it gave different numbers from your paper.
         model          calculated          reported in paper
shufflenetv2_0.5:   45.6M                     41M
shufflenetv2_1.0:   154.65 M               146M
shufflenetv2_1.5:    311.07M                299M
I wonder whether you will release the tools to get the reported flops?

**Comment by nmaac** [comment]
Hi @zxhr2793 , we compute FLOPs of all conv layers and fc layers.  We do not compute FLOPs of BN layers as they are zero at inference time.
