### ISSUE TITLE
Why is ShuffleNetV1 different from description in paper ?

### ISSUE THREAD

**Issue by LuYanFCP** [megvii-model/ShuffleNet-Series#16]
## Difference

Your code in `ShuffleNetV1/blocks.py`
```
x = self.branch_main_1(x)
if self.group > 1:
    x = self.channel_shuffle(x)
x = self.branch_main_2(x)
```
The channel_shuffle operation is in the next of conv3x3 operation. But in the paper, the channel_shuffle operation occurs before the con3x3 operation.
![image](https://user-images.githubusercontent.com/25530442/65815039-7fa51e00-e21c-11e9-9686-6cd3cc9b0f09.png)

**Comment by vlad3996** [comment]
It does not matter when to do channel shuffle : before Conv2d with groups=num_channels or after it.
