### ISSUE TITLE
channel shuffle method is not same as papers in ShuffleNetV1

### ISSUE THREAD

**Issue by Nankaiming** [megvii-model/ShuffleNet-Series#17]
In the paper, the method of channel shuffle is that  we first reshape the output channel dimension into (g, n), transposing and then flattening it back as the input of next layer. But in the code reimplementation, it is reshaped into (n, g), then transposed and flattened. There is some difference with original paper.

**Comment by nmaac** [comment]
Hi @Nankaiming , the function of channel shuffle is to help the information flowing across feature channels in different groups. Actually the two transposing methods you mentioned achieve the same effect, which doesn't affect the training accuracy.
