### ISSUE TITLE
    img = cv2.resize(img, target_size, interpolation=cv2.INTER_LINEAR)

### ISSUE THREAD

**Issue by xxsgcjwddsg** [megvii-model/ShuffleNet-Series#2]
File "train.py", line 30, in __call__
    img = cv2.resize(img, target_size, interpolation=cv2.INTER_LINEAR)
error: OpenCV(4.0.1) /io/opencv/modules/imgproc/src/resize.cpp:3787: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

**Comment by nmaac** [comment]
Hi xxsgcjwddsg, we didn't meet this error when running the code. Did you follow the instruction to prepare the dataset?  It seems your dataset is not load properly.

**Comment by xxsgcjwddsg** [comment]
Thanks，after using python3, the error is gone.
