### ISSUE TITLE
channel shuffle in ShuffleNetV2 

### ISSUE THREAD

**Issue by haochange** [megvii-model/ShuffleNet-Series#21]
在shufflenet中，我画了一个特征图的流程图，发现了一个奇怪的地方，向您请教一下。
![微信图片_20191106170906](https://user-images.githubusercontent.com/17872653/68284370-59df2480-00b8-11ea-9a33-670e40bc502a.png)
如图所示：
在channel shuffle之前，我们得到一个2x4xhxw的特征图，并编上序号。
经过channel shuffle之后，特征图分为两个，分别是两个分支的输入。
经过两个分支的block并concate之后如图第三行所示，每个通道的序号仍然是按照在channel shuffle之前的排序得到的。
此时，特征图会进入下一个带channel shuffle的block，首先进行channel shuffle，得到最后一行的特征图，此时我们会发现，原始的每个bach中的特征图并不是按照类似于第二步中的顺序排列的，而是间隔一个通道排列的。每个batch内的特征图没有相邻，请教一下，是我哪里画错了吗？

**Comment by nmaac** [comment]
Hi @haochange , 

你没有画错。 channel shuffle 的目的是不同group之间的信息流通。
