### ISSUE TITLE
pretrained model fatal error

### ISSUE THREAD

**Issue by haroldfry** [megvii-model/ShuffleNet-Series#22]
Hi, I downloaded the pretrained models provided in Onedrive. However when extracting the tar files, I received following error:
tar: This does not look like a tar archive

Would you be more specific about how to use those pretrained models?

Thank you!

**Comment by nmaac** [comment]
Hi @haroldfry ,  

For the usage of the pretrained models, please follow the evaluation step in the readme file to use the pretrained model. 

If you still cannot use the model, please provide the model name and I will check the file integrity.
