### ISSUE TITLE
Can you release your log files for training?

### ISSUE THREAD

**Issue by leeyeehoo** [megvii-model/ShuffleNet-Series#23]
To reduplicate the training details, I' d like to request the log file for your training.

Best

**Comment by nmaac** [comment]
Hi @leeyeehoo , 

For the remaining log files I still have,  I provide the ShuffleNetV2(2.0x) log file here.
Hope that helps with your reproduction. 


[ShuffleNetV2_2.0_log.txt](https://github.com/megvii-model/ShuffleNet-Series/files/3863169/ShuffleNetV2_2.0_log.txt)
