### ISSUE TITLE
How can I use CPU run the saved model

### ISSUE THREAD

**Issue by HLSDG** [megvii-model/ShuffleNet-Series#26]
Hi there, I am using your ShuffleNetV1 code, which is very useful. Thanks a lot! But when I want to use CPU to run the saved model, it has some errors, so do you have some advices? Thank you again!

**Comment by nmaac** [comment]
Hi @HLSDG , it seems quite normal when I run it on CPU, please make sure that your PyTorch environment is installed correctly.
