### ISSUE TITLE
about trained model file

### ISSUE THREAD

**Issue by shaqing** [megvii-model/ShuffleNet-Series#27]
why the trained model file can't be decompressed?

**Comment by nmaac** [comment]
The model files are pickle files, please refer to https://pytorch.org/tutorials/beginner/saving_loading_models.html.

**Comment by shaqing** [comment]
Thank you very much! I have solved my problem with the help of your answer.
I'm  a algorithm engineer from Shenzhen, majoring in machine learning.
I wanna salute you, because i  admire engineer from megvii so much!
