### ISSUE TITLE
comparision between shufflenet+ and oneshot

### ISSUE THREAD

**Issue by liwei46** [megvii-model/ShuffleNet-Series#28]
Hello,

Thanks for sharing the great project.  
I am trying to design an efficient network.

As in the title, between shufflenet+ and oneshot network, which one is the most efficient? 

Thanks,

**Comment by nmaac** [comment]
Hi @liwei46 ,

ShuffleNetV2+ contains Swish and SE modules to achieve higher performance, therefore less efficient than OneShot.
