### ISSUE TITLE
trained models on BaiduYun cannot be extracted correctly

### ISSUE THREAD

**Issue by vraivon** [megvii-model/ShuffleNet-Series#29]
I downloaded ShuffleNetV2.0.5x.pth.tar on BaiduYun, and get error while extract
![Screenshot from 2020-02-11 17-39-20](https://user-images.githubusercontent.com/9550155/74225594-fb989200-4cf5-11ea-83a7-4cf2f56445bc.png)

and I also tried oneDrive , the page will jump to oneDrive's error page.

**Comment by nmaac** [comment]
Hi @vraivon ,

The model files are pickle files, please refer to https://pytorch.org/tutorials/beginner/saving_loading_models.html.

**Comment by vraivon** [comment]
Thank you, i thought it was packed again
