### ISSUE TITLE
channel shuffle in ShuffleNetV2

### ISSUE THREAD

**Issue by Wangzhuoying0716** [megvii-model/ShuffleNet-Series#3]

**Comment by Wangzhuoying0716** [comment]
Thanks a lot for the sharing!  
From the code of ShuffleNetV2/blocks.py, I thought that the channel_shuffle function in the Module plays the role of splitting instead of shuffling. But I didn't see any operations about the real channel-shuffle. I wonder if I had wrong idea about this?  
For another, depthwise convolutions are used in the networks. Then how about the inference speed? If it's much slower with the pytorch implementation?
Thanks !

**Comment by nmaac** [comment]
Hi @Wangzhuoying0716 , 
1) we simply use the _permute()_ function in line #60 to shuffle the order of the channels;
2) we use DWConv on "half" feature maps with a small amount of channel numbers, which may not influence much.

**Comment by Wangzhuoying0716** [comment]
Thanks ! I misunderstood the meaning of 'shuffle' before.
