### ISSUE TITLE
All training log files

### ISSUE THREAD

**Issue by frank-xwang** [megvii-model/ShuffleNet-Series#30]
Hi, Thanks for your excellent work! Could you please release the log files for shufflenetv2_1.0x and shufflenetv2_0.5x? Thank you so much!

**Comment by nmaac** [comment]
Hi @frank-xwang ,

Attached please find the ShuffleNetV2(0.5x, 1.0x) log files here.
Hope that helps with your reproduction.

[ShuffleNetV2_1.0x.log](https://github.com/megvii-model/ShuffleNet-Series/files/4229278/ShuffleNetV2_1.0x.log)
[ShuffleNetV2_0.5x.log](https://github.com/megvii-model/ShuffleNet-Series/files/4229276/ShuffleNetV2_0.5x.log)

**Comment by frank-xwang** [comment]
Thank you so much!
