### ISSUE TITLE
Compare the speed of mobilenetv3-large, shufflenetv2 1.5x, shufflenetv2 + medium?

### ISSUE THREAD

**Issue by luoduo21** [megvii-model/ShuffleNet-Series#31]
Compare the speed of mobilenetv3-large, shufflenetv2 1.5x, shufflenetv2 + medium based on ncnn on Android CPU. Shufflenetv2 + (154ms) = mobilenetv3-large (157ms)> shufflenetv2 1.5x (166ms), why is v2 + faster than v2 1.5x? Is this reasonable？thank you!

**Comment by nmaac** [comment]
Hi @luoduo21 ,

The speed test on Android is different from GPU (#25).
To get an accurate speed measurement, please test after a period of time and avoid the heating of the mobile equipment.

**Comment by luoduo21** [comment]
Hi @nmaac ,
Of course I test the average time . About of shufflev2 + medium and shufflenetv2 1.5x, I want to know which one is faster on Android（arm） cpu. I tested v2 1.5x which is faster on PC cpu based on pytorch, but the opposite on Android（arm）cpu. Thank you!

**Comment by nmaac** [comment]
Hi @luoduo21 ,
It is not the **_average time_**, I am saying there should be **_a time interval between two tests_**. Because the cpu will heat up after continuous testing, which affects the speed measurement.
