### ISSUE TITLE
No image normalization needed?

### ISSUE THREAD

**Issue by pauloamed** [megvii-model/ShuffleNet-Series#34]
Hi! Congratulations on the awesome work here!

I was trying to use the ShuffleNetV2 on my own dataset and I didn't find any normalization transform on the `train.py` file. Isn't there any?

Best regards,
Paulo

**Comment by nmaac** [comment]
Hi @pauloamed , we do not use normalization transform when we train on ImageNet. It is okay if you want to add it on your own dataset.

**Comment by pauloamed** [comment]
Ok, thanks! But for using the pretrained model you guys provide, I will need to stick w/ no normalization, right?

**Comment by nmaac** [comment]
Yes please make sure training and testing are consistent.

**Comment by pauloamed** [comment]
Thanks!
