### ISSUE TITLE
Questions of Tab.2 in ShuffleNetV2 paper 

### ISSUE THREAD

**Issue by colorjam** [megvii-model/ShuffleNet-Series#35]
Hi, thanks for your interesting work. I'm curious about the details of Tab.2 in ShuffleNetV2 paper. 
1. What are x1, x2, x4 mean? Are they denote the scale of the channel?
2. I try to reproduce the model of g=8 and c=180, while `raise ValueError('in_channels must be divisible by groups')`. Is it a correct setting?

**Comment by nmaac** [comment]
Hi @colorjam , x1, x2, x4 are channel multipliers, and it should be c=184 which is a typo, thanks for point out. To reproduce just make sure keep the FLOPs in each column the same by changing c.
