### ISSUE TITLE
训练时，数据tensor没有做 0~1的归一化么？

### ISSUE THREAD

**Issue by zgsxwsdxg** [megvii-model/ShuffleNet-Series#38]
你好！首先感谢你们的工作！
          我看了你们的训练代码，发现imagefolder 导入图像数据后 没找到做 0~1的归一化，这样对于训练效果有影响不？谢谢

**Comment by nmaac** [comment]
@zgsxwsdxg 不影响，只需确保训练和测试时一致

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 不影响，只需确保训练和测试时一致

我还想问下您，就是归一化后和不归一化对于训练收敛和acc，有区别不？

**Comment by nmaac** [comment]
> > @zgsxwsdxg 不影响，只需确保训练和测试时一致
> 
> 我还想问下您，就是归一化后和不归一化对于训练收敛和acc，有区别不？

没有区别
