### ISSUE TITLE
What algorithms did author use to search the architecture of ShuffleNetV2+?

### ISSUE THREAD

**Issue by jianghaojun** [megvii-model/ShuffleNet-Series#41]
The architecture of ShuffleNetV2+ is quiet different from the ShuffleNetV2! There are 4 type of blocks inside ShuffleNetV2+ and the topology of the network is irregular. I guess some NAS algorithms were adopted to search the architecture. I am curious about the searching algorithms and I hope to get more details about them! Thanks a lot!

**Comment by nmaac** [comment]
The ShuffleNetV2+ architecture is based on the [one-shot NAS model](https://github.com/megvii-model/ShuffleNet-Series/tree/master/OneShot), with additional SE and hswish modules.

**Comment by jianghaojun** [comment]
Thanks for your quick reply to my question! I will try to use one-shot NAS on my own model.

**Comment by jianghaojun** [comment]
The performance of ShuffleNetV2+ is promising. I am curious about the how many iterations or epochs did you use to train the network? Except label smoothing, did you use any other training technics to train the network?
