### ISSUE TITLE
network

### ISSUE THREAD

**Issue by czy112** [megvii-model/ShuffleNet-Series#43]
Do you think the experiment is reasonable if only the SE layer similar to Mobilenetv3 is added into the Shufflenetv2 during the experiment? I tried to test it on some of the data sets and found an improvement, but not a significant one. Looking forward to your reply and comments. Thank you

**Comment by nmaac** [comment]
@czy112 The SE module can improve the performance significantly. Please refer to the usage in [ShuffleNetV2+](https://github.com/megvii-model/ShuffleNet-Series/blob/master/ShuffleNetV2%2B/blocks.py).
