### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Never-mystery** [megvii-model/ShuffleNet-Series#44]
您好 Trained Models里面的ShuffleNetV2 2.0x可能放错了 精度不太对 能麻烦您再提供下这个的Pretrained model吗 谢谢

**Comment by nmaac** [comment]
你好，我们检查过没问题的，请参考 issue  #29 #27 #22 如果你遇到类似的问题

**Comment by Never-mystery** [comment]
您好 确实没问题 应该是我的程序出问题了 谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-model/ShuffleNet-Series"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 中午11:07
收件人:&nbsp;"megvii-model/ShuffleNet-Series"<ShuffleNet-Series@noreply.github.com&gt;;
抄送:&nbsp;"尤江华"<664968027@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [megvii-model/ShuffleNet-Series] Pretrained model (#44)





 
你好，我们检查过没问题的，请参考 issue  #29 #27 #22 如果你遇到类似的问题
