### ISSUE TITLE
Traceback and AssertionError in train

### ISSUE THREAD

**Issue by larifreitas** [megvii-model/ShuffleNet-Series#45]
Traceback (most recent call last):
  File "train.py", line 286, in <module>
    main()
  File "train.py", line 107, in main
    assert os.path.exists(args.train_dir)
AssertionError

$  python3 train.py --model-size 1.5x --train-dir=pessoa/train/*.jpg --val-dir=pessoa/test/*.jpg --save=./models/

**Comment by nmaac** [comment]
it is an assertion error because your train directory is incorrect

**Comment by larifreitas** [comment]
@nmaac when I copied from the terminal to the description of the question it went wrong.
the way I did it was:

`python3 train.py --model-size 1.5x --train-dir=pessoa/train/*.jpg --val-dir=pessoa/test/*.jpg --save=./models/`

is it still wrong?

thank u so much!!!

**Comment by nmaac** [comment]
> @nmaac when I copied from the terminal to the description of the question it went wrong.
> the way I did it was:
> 
> `python3 train.py --model-size 1.5x --train-dir=pessoa/train/*.jpg --val-dir=pessoa/test/*.jpg --save=./models/`
> 
> is it still wrong?
> 
> thank u so much!!!

train_dir is a parameter in torchvision.datasets.ImageFolder, please make sure this directory path is this format: [api doc](https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder)

**Comment by larifreitas** [comment]
@nmaac I'm new to all of this, I couldn't understand what was going on.
but a lot thanks for the help!!
