### ISSUE TITLE
question on why 4 fragments in parallel runs slower than 4 fragments in series

### ISSUE THREAD

**Issue by guochengqian** [megvii-model/ShuffleNet-Series#46]
Dear @nmaac ,

May I ask a question w.r.t ShuffleNet v2?
Why 4 fragments in parallel run slower than 4 fragments in series? 
The 4 fragments in parallel does not compute in parallel fashion? Is that due to implementation issue? Does that mean inception module actually does now increase speed but decrease it? 

Thank you!

**Comment by nmaac** [comment]
Hi @guochengqian , 
We use Table 4 to show that more-fragmented structures (both in parallel and in series) run slower than less-fragmented structures.
The speed differences between structures in parallel and in series, which is beyond the focus of that paper, are negligible comparing with the differences among 1/2/4-fragmented structures.

**Comment by guochengqian** [comment]
Okay. Thank you.
