### ISSUE TITLE
通道设计不是2^n的原因

### ISSUE THREAD

**Issue by harleyszhang** [megvii-model/ShuffleNet-Series#47]
1，shuffleNet v2的通道数设计为什么不是像resnet, mobilenet等backbone网络按照2^n方那样设计，这个通道数是nas搜索出来的吗，我看论文没有提到通道数设计的来源。
2，如果是目标检测网络的backbone换成了shuffleNet v2，但是通道数设计为32，64，128这种2^n方类型，精度是不是会下降。

**Comment by nmaac** [comment]
1. 我们在文中提到，调整通道数控制FLOPs。需要调整通道数将FLOPs与之前工作对齐从而公平对比，与NAS无关。
2. 同理，需要控制FLOPs公平对比，2^n通道数与精度无关。

**Comment by harleyszhang** [comment]
我可以理解为论文表 5 中的那种通道数设计和精度并没有关系吧，从而我把 shufflenetv2 作为目标检测的 backbone，可以对通道数进行修改为 2^n，这是不会影响 backbone 本身的精度.

**Comment by nmaac** [comment]
精度与FLOPs有关，与是否为2^n无关
