### ISSUE TITLE
原则2中为什么 MAC 与组数  g 成正比的问题

### ISSUE THREAD

**Issue by harleyszhang** [megvii-model/ShuffleNet-Series#48]
![image](https://user-images.githubusercontent.com/37138671/110648082-5e0edb00-81f3-11eb-96b5-7c09762948ab.png)
原则2中的公式(2)给定输入特征图尺寸（shape） 和计算代价 B，则 MAC 与组数  g 成正比，这里我有些不明白，B 本身就与 g 有关系，而且对公式进行换算后，不是MAC 与组数  g 成反比吗？

**Comment by nmaac** [comment]
给定输入特征图hwc1，为保证B不变，需调整g和c2，消掉c2得到如公式所述的MAC与g的正比关系

**Comment by harleyszhang** [comment]
你想表达的应该是，固定 c2/g 的值，又因为 hwc1 固定，从而也就固定了 B 值，所以可得 （2）式 MAC 与 g 成正比。我这样理解没问题吧。
