### ISSUE TITLE
channel shuffle layer's location

### ISSUE THREAD

**Issue by desktoop** [megvii-model/ShuffleNet-Series#49]
In this paper [_ShuffleNet: An Extremely Convolution Neural Network for Mobile Device_](https://arxiv.org/abs/1707.01083) , 
residual branch in shufflenet unit is seems like pw->channel shuffle->dw->pw. But in this repo, residual branch is pw->dw->channel shuffle->pw.
Why the order of those layers are different?

**Comment by nmaac** [comment]
This is a duplicate issue of #16, #39
