### ISSUE TITLE
One shot accuracy

### ISSUE THREAD

**Issue by pawopawo** [megvii-model/ShuffleNet-Series#5]
[oneshot.txt](https://github.com/megvii-model/ShuffleNet-Series/files/3539541/oneshot.txt)
The error rate of my training is 26.3, can't reach 25.1.

**Comment by wy113856** [comment]
same problem, Top-1 err = 0.260400
Is there any other training tricks? like warm up? mini batch?

**Comment by nmaac** [comment]
Hi @xxsgcjwddsg , we trained the searched model multiple times and got 25.1~25.6, the average of which is 25.3. The log you supply shows obvious under-fit which never occurs in our experiments.  We suggest you check and train it again, thanks.
