### ISSUE TITLE
Question about Fig.2

### ISSUE THREAD

**Issue by AaronStuart** [megvii-model/ShuffleNet-Series#54]
Hi, your run time decomposition is really amazing ! It's very useful for analysis network inference time. I'm curious about how do you measure these time? And what's the "Data" mean ?
![image](https://user-images.githubusercontent.com/21955436/130791756-6165e3f1-33a8-43a6-bf6a-3ee57d343f54.png)

**Comment by nmaac** [comment]
1. By a megengine tool: https://megengine.org.cn/doc/stable/zh/user-guide/tools/load-and-run.html#load-and-run
2. data loading time
