### ISSUE TITLE
channel shuffle

### ISSUE THREAD

**Issue by fengchen321** [megvii-model/ShuffleNet-Series#59]
V1里用了通道重排，为啥v2没有使用，2里面的通道重排函数只是一个split，block最后concat之后就没有channel shuffle

**Comment by megvii-model** [comment]
channel shuffle写在了每个block最开始，刚好就是上一个block concat之后的地方：
https://github.com/megvii-model/ShuffleNet-Series/blob/aa91feb71b01f28d0b8da3533d20a3edb11b1810/ShuffleNetV2/blocks.py#L49

**Comment by fengchen321** [comment]
感谢回复，我明白了

**Comment by WuSiYu** [comment]
@megvii-model 你好，请问repo中关于shufflenetV2的channel_shuffle的使用是否和论文中的与torchvision中的实现不同？

repo中仅在stride==1时经过channel_shuffle，但论文和torchvision实现中均为总是经过channel_shuffle，无论stride是1还是2:

https://github.com/megvii-model/ShuffleNet-Series/blob/aa91feb71b01f28d0b8da3533d20a3edb11b1810/ShuffleNetV2/blocks.py#L47-L54

https://github.com/pytorch/vision/blob/d0e16b7607f8ce53e190fe286dcc338c6dc8a3cc/torchvision/models/shufflenetv2.py#L99

导出ONNX模型用Netron观察也是和从torchvision导出的不同
