### ISSUE TITLE
About BN operations recalculation

### ISSUE THREAD

**Issue by johannwyh** [megvii-model/ShuffleNet-Series#9]
Hello, first and foremost, thank you for sharing your paper works.

You said in your paper of **Single Path One-Shot** that: 

> Before the inference of an architecture, the statistics of all the BN operations are recalculated on a ramdom subset of training data.

I have some questions on **the recalculation**:

1. How much does this recalculation affects the inference and evolutionary search?
2. How do you achieve this? Is it something like firstly turning off all the parameters' _training_ switch , then turning those BNs' on, finally do training (BP) on the model using the subset of data?
3. Is subset of training data re-sampled everytime a new architecture is given? or the contents of the subset are sampled only once and do not change during evolutionary search?

Thank you so much if you can give me some idea.

**Comment by nmaac** [comment]
Hi @johannwyh ,
1. It would be unstable without using recalculation.
2. No. Each time after training and before inference, we recalculate mean and val on a random training dataset.
3. It doesn't affect much between re-sample each time and use the fix set.
